{{- $rearControllerConfig := (merge (dict "name" "rear-controller" "module" "rear-controller") .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "fluidos.labels" $rearControllerConfig | nindent 4 }}
  name: {{ include "fluidos.prefixedName" $rearControllerConfig }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.rearController.replicas }}
  selector:
    matchLabels:
      {{- include "fluidos.labels" $rearControllerConfig | nindent 6 }}
  template:
    metadata: 
    {{ if .Values.rearController.pod.annotations }}
      annotations:
        {{- toYaml .Values.rearController.pod.annotations | nindent 8 }}
    {{ end }}
      labels:
        {{- include "fluidos.labels" $rearControllerConfig | nindent 8 }}
      {{ if .Values.rearController.pod.labels }}
        {{ toYaml .Values.rearController.pod.labels | nindent 8 }}
      {{ end }}
    spec:
      {{- if gt .Values.rearController.replicas 1.0 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "fluidos.labels" $rearControllerConfig | nindent 18 }}
              topologyKey: kubernetes.io/hostname
      {{- end }}
      securityContext:
        {{- include "fluidos.podSecurityContext" $rearControllerConfig | nindent 8 }}
      serviceAccountName: {{ include "fluidos.prefixedName" $rearControllerConfig }}
      containers:
      - image: {{ .Values.rearController.imageName }}:{{ include "fluidos.version" $rearControllerConfig }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        securityContext:
          {{- include "fluidos.containerSecurityContext" $rearControllerConfig | nindent 10 }}
        name: {{ $rearControllerConfig.name }}
        command: ["/usr/bin/rear-controller"]
        args:
          - --grpc-port={{ .Values.rearController.service.grpc.port }}
          - --http-port={{ .Values.rearController.service.gateway.port }}
        resources: {{- toYaml .Values.rearController.pod.resources | nindent 10 }}
        ports:
        - name: healthz
          containerPort: 8081
          protocol: TCP
        - name: {{ .Values.rearController.service.gateway.name }}
          containerPort: {{ .Values.rearController.service.gateway.port }}
          protocol: TCP
        - name: {{ .Values.rearController.service.grpc.name }}
          containerPort: {{ .Values.rearController.service.grpc.port }}
          protocol: TCP
        - name: webhook
          containerPort: 9443
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        volumeMounts:
        - name: webhook-certs
          mountPath: {{ .Values.webhook.deployment.certsMount | default "/tmp/k8s-webhook-server/serving-certs/" }}
      volumes:
      - name: webhook-certs
        secret:
          secretName: {{ include "fluidos.prefixedName" $rearControllerConfig }}
      {{- if (.Values.common).nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.common.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if ((.Values.common).tolerations) }}
      tolerations:
      {{- toYaml .Values.common.tolerations | nindent 8 }}
      {{- end }}
      {{- if ((.Values.common).affinity) }}
      affinity:
      {{- toYaml .Values.common.affinity | nindent 8 }}
      {{- end }}

