---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - advertisement.fluidos.eu
  resources:
  - discoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - advertisement.fluidos.eu
  resources:
  - discoveries/finalizers
  verbs:
  - update
- apiGroups:
  - advertisement.fluidos.eu
  resources:
  - discoveries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nodecore.fluidos.eu
  resources:
  - solvers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodecore.fluidos.eu
  resources:
  - solvers/finalizers
  verbs:
  - update
- apiGroups:
  - nodecore.fluidos.eu
  resources:
  - solvers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - reservation.fluidos.eu
  resources:
  - reservations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reservation.fluidos.eu
  resources:
  - reservations/finalizers
  verbs:
  - update
- apiGroups:
  - reservation.fluidos.eu
  resources:
  - reservations/status
  verbs:
  - get
  - patch
  - update
