kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.28.0
  - role: worker
    labels:
      node-role.fluidos.eu/resources: "true"
      node-role.fluidos.eu/worker: "true"
    image: kindest/node:v1.28.0
  - role: worker
    image: kindest/node:v1.28.0
    labels:
      node-role.fluidos.eu/resources: "true"